(print("CUSTOMER FEEDBACK FORM"))
name = input("Enter your name: ") 
feedback = input("Enter your feedback: ")
name=(name.title())
feedback=(feedback.strip().rstrip())
print("customer feedback")
print("Enter customer name:",name)
print("Enter feedback:",feedback)
