Name =input("Enter Name:-")
CollegeName=input("Enter College Name:-")
RollNo=(input("Enter Roll No:-"))
StudentAge=(input("Enter Student Age:-"))
Add=input("Enter Address:-")
print("**********Student Details**********")
print("My Name is ",Name)
print("My college Name is ",CollegeName)
print("My Roll No is ",RollNo)
print("My age is ",StudentAge)
print("My Address is ",Add)
