name =input("Enter your name -:")

print(name.upper())
print(name.title())
print(name.capitalize())
print(name.swapcase())
print(name.strip())
print(name.lstrip())
print(name.rstrip())
print(name.replace("shreyas", "shreyash"))
print(name.split())
print(name.find("h"))
print(name.count("s"))
print(name.center(60))
print(name.rjust(200))
print(name.ljust(100))
